server:
  port: 8081
spring:
  application:
    version: Customer Service v111111
  datasource:
    url: jdbc:postgresql://localhost:5432/dbcustomer
    username: developer
    password: supersecretpassword
    hikari:
      minimumIdle: 2
      maximumPoolSize: 5
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


management:
  endpoints:
    actuator: true
    web:
      exposure:
        include: "*"
